apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-cfg
  namespace: nginx
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <title>Welcome to My Simple Nginx Service</title>
    </head>
    <body>
        <h1>Nephio Demo Project</h1>
    </body>
    </html>
